// <auto-generated />
using System;
using GoldwallApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldwallApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429223250_IFormFileIntegration")]
    partial class IFormFileIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldwallApp.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusinessId");

                    b.ToTable("Business", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ClientId");

                    b.HasIndex("BusinessId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.DefectReport", b =>
                {
                    b.Property<int>("DefectReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefectReportId"));

                    b.Property<int>("DefectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FixEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("int");

                    b.Property<int?>("SuspectedCauseEventId")
                        .HasColumnType("int");

                    b.HasKey("DefectReportId");

                    b.HasIndex("DefectTypeId");

                    b.HasIndex("SurfaceId");

                    b.ToTable("DefectReport", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.DefectType", b =>
                {
                    b.Property<int>("DefectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefectTypeId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DefectTypeId");

                    b.HasIndex("BusinessId");

                    b.ToTable("DefectType", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.EventContext", b =>
                {
                    b.Property<int>("WorkEventId")
                        .HasColumnType("int");

                    b.Property<decimal>("HumidityPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("MixRatio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TemperatureC")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TimeSincePrevEventHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("VentilationRating")
                        .HasColumnType("int");

                    b.HasKey("WorkEventId");

                    b.HasIndex("MaterialId");

                    b.ToTable("EventContext", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.EventOutcome", b =>
                {
                    b.Property<int>("WorkEventId")
                        .HasColumnType("int");

                    b.Property<decimal>("DryTimeHoursActual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("QualityRating")
                        .HasColumnType("int");

                    b.Property<bool>("ReworkRequired")
                        .HasColumnType("bit");

                    b.HasKey("WorkEventId");

                    b.ToTable("EventOutcome");
                });

            modelBuilder.Entity("GoldwallApp.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("Categoery")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventTypeId");

                    b.HasIndex("BusinessId");

                    b.ToTable("EventType", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.EvidencePhoto", b =>
                {
                    b.Property<int>("EvidencePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidencePhotoId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("DefectReportId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkEventId")
                        .HasColumnType("int");

                    b.HasKey("EvidencePhotoId");

                    b.HasIndex("DefectReportId");

                    b.HasIndex("WorkEventId");

                    b.ToTable("EvidencePhoto", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDatePlanned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDatePlanned")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ClientId");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId");

                    b.HasIndex("BusinessId");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Pattern", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PatternId");

                    b.HasIndex("BusinessId");

                    b.ToTable("Pattern", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.PatternOutcome", b =>
                {
                    b.Property<int>("PatternOutcomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternOutcomeId"));

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OutcomeMetric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatternId")
                        .HasColumnType("int");

                    b.Property<decimal>("Probability")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("PatternOutcomeId");

                    b.HasIndex("PatternId");

                    b.ToTable("PatternOutcome", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.PatternRule", b =>
                {
                    b.Property<int>("PatternRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternRuleId"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PatternId")
                        .HasColumnType("int");

                    b.Property<string>("Value1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PatternRuleId");

                    b.HasIndex("PatternId");

                    b.ToTable("PatternRule", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoomId");

                    b.HasIndex("JobId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Surface", b =>
                {
                    b.Property<int>("SurfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfaceId"));

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SubstrateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurfaceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SurfaceId");

                    b.HasIndex("RoomId");

                    b.ToTable("Surface", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("BusinessId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.WorkEvent", b =>
                {
                    b.Property<int>("WorkEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkEventId"));

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkEventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("SurfaceId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkEvent", (string)null);
                });

            modelBuilder.Entity("GoldwallApp.Models.Client", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("Clients")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("GoldwallApp.Models.DefectReport", b =>
                {
                    b.HasOne("GoldwallApp.Models.DefectType", "DefectType")
                        .WithMany("DefectReports")
                        .HasForeignKey("DefectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldwallApp.Models.Surface", "Surface")
                        .WithMany("DefectReports")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectType");

                    b.Navigation("Surface");
                });

            modelBuilder.Entity("GoldwallApp.Models.DefectType", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("DefectTypes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("GoldwallApp.Models.EventContext", b =>
                {
                    b.HasOne("GoldwallApp.Models.Material", "Material")
                        .WithMany("EventContexts")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldwallApp.Models.WorkEvent", "WorkEvent")
                        .WithOne("EventContext")
                        .HasForeignKey("GoldwallApp.Models.EventContext", "WorkEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("WorkEvent");
                });

            modelBuilder.Entity("GoldwallApp.Models.EventOutcome", b =>
                {
                    b.HasOne("GoldwallApp.Models.WorkEvent", "WorkEvent")
                        .WithOne("EventOutcome")
                        .HasForeignKey("GoldwallApp.Models.EventOutcome", "WorkEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkEvent");
                });

            modelBuilder.Entity("GoldwallApp.Models.EventType", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("EventTypes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("GoldwallApp.Models.EvidencePhoto", b =>
                {
                    b.HasOne("GoldwallApp.Models.DefectReport", "DefectReport")
                        .WithMany("EvidencePhotos")
                        .HasForeignKey("DefectReportId");

                    b.HasOne("GoldwallApp.Models.WorkEvent", "WorkEvent")
                        .WithMany("EvidencePhotos")
                        .HasForeignKey("WorkEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectReport");

                    b.Navigation("WorkEvent");
                });

            modelBuilder.Entity("GoldwallApp.Models.Job", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("Jobs")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldwallApp.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoldwallApp.Models.Material", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("Materials")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("GoldwallApp.Models.Pattern", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("Patterns")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("GoldwallApp.Models.PatternOutcome", b =>
                {
                    b.HasOne("GoldwallApp.Models.Pattern", "Pattern")
                        .WithMany("PatternOutcomes")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("GoldwallApp.Models.PatternRule", b =>
                {
                    b.HasOne("GoldwallApp.Models.Pattern", "Pattern")
                        .WithMany("PatternRules")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("GoldwallApp.Models.Room", b =>
                {
                    b.HasOne("GoldwallApp.Models.Job", "Job")
                        .WithMany("Rooms")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("GoldwallApp.Models.Surface", b =>
                {
                    b.HasOne("GoldwallApp.Models.Room", "Room")
                        .WithMany("Surfaces")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GoldwallApp.Models.User", b =>
                {
                    b.HasOne("GoldwallApp.Models.Business", "Business")
                        .WithMany("Users")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("GoldwallApp.Models.WorkEvent", b =>
                {
                    b.HasOne("GoldwallApp.Models.EventType", "EventType")
                        .WithMany("WorkEvents")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldwallApp.Models.Surface", "Surface")
                        .WithMany("WorkEvents")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldwallApp.Models.User", "User")
                        .WithMany("WorkEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Surface");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoldwallApp.Models.Business", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("DefectTypes");

                    b.Navigation("EventTypes");

                    b.Navigation("Jobs");

                    b.Navigation("Materials");

                    b.Navigation("Patterns");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GoldwallApp.Models.DefectReport", b =>
                {
                    b.Navigation("EvidencePhotos");
                });

            modelBuilder.Entity("GoldwallApp.Models.DefectType", b =>
                {
                    b.Navigation("DefectReports");
                });

            modelBuilder.Entity("GoldwallApp.Models.EventType", b =>
                {
                    b.Navigation("WorkEvents");
                });

            modelBuilder.Entity("GoldwallApp.Models.Job", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GoldwallApp.Models.Material", b =>
                {
                    b.Navigation("EventContexts");
                });

            modelBuilder.Entity("GoldwallApp.Models.Pattern", b =>
                {
                    b.Navigation("PatternOutcomes");

                    b.Navigation("PatternRules");
                });

            modelBuilder.Entity("GoldwallApp.Models.Room", b =>
                {
                    b.Navigation("Surfaces");
                });

            modelBuilder.Entity("GoldwallApp.Models.Surface", b =>
                {
                    b.Navigation("DefectReports");

                    b.Navigation("WorkEvents");
                });

            modelBuilder.Entity("GoldwallApp.Models.User", b =>
                {
                    b.Navigation("WorkEvents");
                });

            modelBuilder.Entity("GoldwallApp.Models.WorkEvent", b =>
                {
                    b.Navigation("EventContext");

                    b.Navigation("EventOutcome");

                    b.Navigation("EvidencePhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
